### ISSUE TITLE
Why is modified always set to true before I type anything?

### ISSUE THREAD

**Issue by shredmaster** [xrado/vue-validator#5]
Is there any reason why each input field is validated upon page reload? I only want to set "valid" or "invalid" when user start typing. 

validator
{
	"name": {
		"_validate": {
			"required": "required"
		},
		"required": true,
		"modified": true,
		"valid": true
	},
	"location": {
		"_validate": {
			"location": "location"
		},
		"location": false,
		"modified": true,
		"valid": false
	}
}

form object
{
	"name": ""
}

**Comment by xrado** [comment]
because sometimes you may also have to validate form that is already filled with data. Make a fiddle with your example.

**Comment by shredmaster** [comment]
see my comment on https://github.com/xrado/vue-validator/issues/4
